import type { CodexUsageExportFormat, CodexUsageInvestigation } from '@/shared/contracts/codex-usage';
import type { CodexUsageInternalRow } from '@/main/extensions/codex-usage-investigator/session-reader';

function csvCell(value: string | number | null) {
  if (value === null) return '';
  let text = String(value);
  if (/^[=+\-@\t\r]/.test(text)) text = `'${text}`;
  return /[",\r\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text;
}

type CsvRecord = Partial<Record<string, string | number | null>>;

function turnSpeedRows(investigation: CodexUsageInvestigation): CsvRecord[] {
  const analysis = investigation.turnSpeed;
  if (!analysis) return [];
  return [
    {
      record_kind: 'TURN_SPEED_SUMMARY',
      analysis_scope: 'COVERAGE',
      generated_at: investigation.generatedAt,
      range: investigation.range,
      time_zone: investigation.timeZone,
      algorithm_version: analysis.algorithmVersion,
      analysis_definition: analysis.definition,
      comparison_scope: analysis.comparisonScope,
      range_assignment: analysis.rangeAssignment,
      official_speed_multiplier: analysis.officialSpeedMultiplier,
      completed_turn_count: analysis.completedTurnCount,
      valid_turn_count: analysis.validTurnCount,
      comparable_turn_count: analysis.comparableTurnCount,
      excluded_invalid_duration_turn_count: analysis.excludedInvalidDurationTurnCount,
      excluded_unknown_service_tier_turn_count: analysis.excludedUnknownServiceTierTurnCount,
      excluded_unknown_cohort_turn_count: analysis.excludedUnknownCohortTurnCount,
      valuation_kind: 'completed_turn_median_duration_ratio',
    },
    ...analysis.comparisons.map((comparison) => ({
      record_kind: 'TURN_SPEED_COMPARISON',
      analysis_scope: 'CONTROLLED_COMPARISON',
      generated_at: investigation.generatedAt,
      range: investigation.range,
      time_zone: investigation.timeZone,
      algorithm_version: analysis.algorithmVersion,
      analysis_definition: analysis.definition,
      comparison_scope: analysis.comparisonScope,
      range_assignment: analysis.rangeAssignment,
      model: comparison.model,
      reasoning_effort: comparison.reasoningEffort,
      standard_turn_count: comparison.standard.completedTurnCount,
      fast_turn_count: comparison.fast.completedTurnCount,
      standard_median_duration_ms: comparison.standard.medianDurationMs,
      fast_median_duration_ms: comparison.fast.medianDurationMs,
      official_speed_multiplier: analysis.officialSpeedMultiplier,
      actual_speed_multiplier: comparison.actualSpeedMultiplier,
      completed_turn_count: analysis.completedTurnCount,
      valid_turn_count: analysis.validTurnCount,
      comparable_turn_count: analysis.comparableTurnCount,
      excluded_invalid_duration_turn_count: analysis.excludedInvalidDurationTurnCount,
      excluded_unknown_service_tier_turn_count: analysis.excludedUnknownServiceTierTurnCount,
      excluded_unknown_cohort_turn_count: analysis.excludedUnknownCohortTurnCount,
      valuation_kind: 'completed_turn_median_duration_ratio',
    })),
  ];
}

function quotaCycleRows(investigation: CodexUsageInvestigation): CsvRecord[] {
  return (investigation.quotaYield?.cycles ?? []).map((cycle) => ({
    record_kind: 'QUOTA_OBSERVATION_SEGMENT',
    generated_at: investigation.generatedAt,
    range: investigation.range,
    time_zone: investigation.timeZone,
    granularity: investigation.granularity,
    algorithm_version: investigation.quotaYield?.algorithmVersion ?? null,
    calculation_basis: investigation.quotaYield?.calculationBasis ?? null,
    plan_type: cycle.planType,
    limit_id: cycle.limitId,
    quota_kind: cycle.quotaKind,
    window_kind: cycle.windowKind,
    window_duration_minutes: cycle.windowDurationMins,
    tokens_per_subscription_quota_1_percent: cycle.tokensPerOnePercent,
    standard_equivalent_tokens_per_subscription_quota_1_percent: cycle.standardEquivalentTokensPerOnePercent,
    median_non_cached_tokens_per_1_percent: cycle.nonCachedTokensPerOnePercent,
    standard_equivalent_non_cached_tokens_per_1_percent: cycle.standardEquivalentNonCachedTokensPerOnePercent,
    cached_input_percent: cycle.cachedInputPercent,
    sample_count: 1,
    quota_percent_observed: cycle.quotaPercentConsumed,
    sample_from: cycle.observedFrom,
    sample_to: cycle.observedTo,
    cycle_starts_at: cycle.startsAt,
    previous_used_percent: cycle.baselineUsedPercent,
    current_used_percent: cycle.maximumUsedPercent,
    resets_at: cycle.resetsAt,
    requests: cycle.requestCount,
    input_tokens: cycle.inputTokens,
    cached_input_tokens: cycle.cachedInputTokens,
    cache_write_input_tokens: cycle.cacheWriteInputTokens,
    output_tokens: cycle.outputTokens,
    reasoning_output_tokens: cycle.reasoningOutputTokens,
    total_tokens: cycle.totalTokens,
    standard_equivalent_total_tokens: cycle.standardEquivalentTokens,
    standard_equivalent_api_usd: cycle.standardEquivalentApiUsd,
    model_token_shares: JSON.stringify(cycle.modelShares),
    valuation_kind: 'weekly_quota_observation_segment_raw_and_standard_equivalent_tokens',
  }));
}

function sessionLengthRows(investigation: CodexUsageInvestigation): CsvRecord[] {
  const analysis = investigation.sessionLength;
  if (!analysis) return [];
  const coverage: CsvRecord = {
    record_kind: 'SESSION_LENGTH_SUMMARY',
    analysis_scope: 'COVERAGE',
    generated_at: investigation.generatedAt,
    range: investigation.range,
    time_zone: investigation.timeZone,
    algorithm_version: analysis.algorithmVersion,
    analysis_definition: analysis.definition,
    comparison_scope: analysis.comparisonScope,
    bucket_strategy: analysis.bucketStrategy,
    range_assignment: analysis.rangeAssignment,
    context_definition: analysis.contextDefinition,
    signal_minimum_sessions: analysis.signalMinimumSessions,
    signal_minimum_priced_sessions: analysis.signalMinimumPricedSessions,
    source_session_count: analysis.sourceSessionCount,
    range_session_count: analysis.rangeSessionCount,
    comparison_session_count: analysis.comparisonSessionCount,
    excluded_unsupported_source_sessions: analysis.excludedUnsupportedSourceSessionCount,
    excluded_incomplete_sessions: analysis.excludedIncompleteSessionCount,
    excluded_no_owned_turn_sessions: analysis.excludedNoOwnedTurnSessionCount,
    excluded_open_sessions: analysis.excludedOpenSessionCount,
    excluded_outside_range_sessions: analysis.excludedOutsideRangeSessionCount,
    excluded_no_usage_sessions: analysis.excludedNoUsageSessionCount,
    excluded_unknown_model_sessions: analysis.excludedUnknownModelSessionCount,
    excluded_mixed_model_sessions: analysis.excludedMixedModelSessionCount,
    mixed_service_tier_sessions: analysis.mixedServiceTierSessionCount,
    unknown_service_tier_sessions: analysis.unknownServiceTierSessionCount,
    valuation_kind: 'complete_session_event_date_standard_api_equivalent_per_owned_chat_turn',
  };
  return [
    coverage,
    ...analysis.comparisons.flatMap((comparison) => {
      const lowestTokenRanges = new Set(
        comparison.lowestMedianTokenRanges.map(({ minimumTurns, maximumTurns }) => `${minimumTurns}:${maximumTurns}`),
      );
      const lowestApiRanges = new Set(
        comparison.lowestMedianApiCostRanges.map(({ minimumTurns, maximumTurns }) => `${minimumTurns}:${maximumTurns}`),
      );
      return [
        {
          record_kind: 'SESSION_LENGTH_SUMMARY',
          analysis_scope: 'CONTROLLED_COMPARISON',
          generated_at: investigation.generatedAt,
          range: investigation.range,
          time_zone: investigation.timeZone,
          algorithm_version: analysis.algorithmVersion,
          analysis_definition: analysis.definition,
          comparison_scope: analysis.comparisonScope,
          bucket_strategy: analysis.bucketStrategy,
          range_assignment: analysis.rangeAssignment,
          context_definition: analysis.contextDefinition,
          signal_minimum_sessions: analysis.signalMinimumSessions,
          signal_minimum_priced_sessions: analysis.signalMinimumPricedSessions,
          session_source: comparison.source,
          model: comparison.model,
          service_tier: 'ALL',
          source_session_count: analysis.sourceSessionCount,
          range_session_count: analysis.rangeSessionCount,
          comparison_session_count: analysis.comparisonSessionCount,
          session_count: comparison.sessionCount,
          total_chat_turns: comparison.totalChatTurns,
          median_session_turns: comparison.medianSessionTurns,
          p90_session_turns: comparison.percentile90SessionTurns,
          maximum_session_turns: comparison.maximumSessionTurns,
          average_context_compactions: comparison.averageContextCompactions,
          api_priced_sessions: comparison.apiPricedSessionCount,
          api_pricing_coverage_percent: comparison.apiPricingCoveragePercent,
          lowest_token_ranges: JSON.stringify(comparison.lowestMedianTokenRanges),
          lowest_api_cost_ranges: JSON.stringify(comparison.lowestMedianApiCostRanges),
          sustained_increase_minimum_turns: comparison.sustainedApiCostIncrease?.minimumTurns ?? null,
          sustained_increase_maximum_turns: comparison.sustainedApiCostIncrease?.maximumTurns ?? null,
          sustained_increase_percent: comparison.sustainedApiCostIncrease?.relativeToLowestPercent ?? null,
          excluded_unsupported_source_sessions: analysis.excludedUnsupportedSourceSessionCount,
          excluded_incomplete_sessions: analysis.excludedIncompleteSessionCount,
          excluded_no_owned_turn_sessions: analysis.excludedNoOwnedTurnSessionCount,
          excluded_open_sessions: analysis.excludedOpenSessionCount,
          excluded_outside_range_sessions: analysis.excludedOutsideRangeSessionCount,
          excluded_no_usage_sessions: analysis.excludedNoUsageSessionCount,
          excluded_unknown_model_sessions: analysis.excludedUnknownModelSessionCount,
          excluded_mixed_model_sessions: analysis.excludedMixedModelSessionCount,
          mixed_service_tier_sessions: analysis.mixedServiceTierSessionCount,
          unknown_service_tier_sessions: analysis.unknownServiceTierSessionCount,
          valuation_kind: 'complete_session_event_date_standard_api_equivalent_per_owned_chat_turn',
        },
        ...comparison.buckets.map((bucket) => ({
          record_kind: 'SESSION_LENGTH_BUCKET',
          analysis_scope: 'CONTROLLED_COMPARISON',
          generated_at: investigation.generatedAt,
          range: investigation.range,
          time_zone: investigation.timeZone,
          algorithm_version: analysis.algorithmVersion,
          analysis_definition: analysis.definition,
          bucket_strategy: analysis.bucketStrategy,
          session_source: comparison.source,
          model: comparison.model,
          service_tier: 'ALL',
          session_turns_minimum: bucket.minimumTurns,
          session_turns_maximum: bucket.maximumTurns,
          session_count: bucket.sessionCount,
          total_chat_turns: bucket.totalChatTurns,
          average_context_compactions: bucket.averageContextCompactions,
          median_uncached_input_tokens_per_turn: bucket.medianUncachedInputTokensPerTurn,
          median_cached_input_tokens_per_turn: bucket.medianCachedInputTokensPerTurn,
          median_cache_write_input_tokens_per_turn: bucket.medianCacheWriteInputTokensPerTurn,
          median_output_tokens_per_turn: bucket.medianOutputTokensPerTurn,
          median_reasoning_output_tokens_per_turn: bucket.medianReasoningOutputTokensPerTurn,
          median_total_tokens_per_turn: bucket.medianTotalTokensPerTurn,
          median_api_equivalent_usd_per_turn: bucket.medianApiEquivalentUsdPerTurn,
          api_priced_sessions: bucket.apiPricedSessionCount,
          api_pricing_coverage_percent: bucket.apiPricingCoveragePercent,
          p25_peak_context_tokens: bucket.percentile25PeakContextTokens,
          p75_peak_context_tokens: bucket.percentile75PeakContextTokens,
          is_lowest_token_range: lowestTokenRanges.has(`${bucket.minimumTurns}:${bucket.maximumTurns}`) ? 1 : 0,
          is_lowest_api_cost_range: lowestApiRanges.has(`${bucket.minimumTurns}:${bucket.maximumTurns}`) ? 1 : 0,
          valuation_kind: 'complete_session_event_date_standard_api_equivalent_per_owned_chat_turn',
        })),
      ];
    }),
  ];
}

const CSV_HEADERS = [
  'record_kind',
  'generated_at',
  'range',
  'time_zone',
  'granularity',
  'algorithm_version',
  'analysis_definition',
  'analysis_scope',
  'comparison_scope',
  'bucket_strategy',
  'range_assignment',
  'reasoning_effort',
  'official_speed_multiplier',
  'actual_speed_multiplier',
  'standard_turn_count',
  'fast_turn_count',
  'standard_median_duration_ms',
  'fast_median_duration_ms',
  'completed_turn_count',
  'valid_turn_count',
  'comparable_turn_count',
  'excluded_invalid_duration_turn_count',
  'excluded_unknown_service_tier_turn_count',
  'excluded_unknown_cohort_turn_count',
  'context_definition',
  'signal_minimum_sessions',
  'signal_minimum_priced_sessions',
  'calculation_basis',
  'attribution',
  'plan_type',
  'limit_id',
  'window_kind',
  'window_duration_minutes',
  'model',
  'service_tier',
  'session_source',
  'inferred_service_tier_tokens',
  'tokens_per_subscription_quota_1_percent',
  'standard_equivalent_tokens_per_subscription_quota_1_percent',
  'mean_tokens_per_1_percent',
  'median_non_cached_tokens_per_1_percent',
  'standard_equivalent_non_cached_tokens_per_1_percent',
  'median_tokens_per_1_percent',
  'p25_tokens_per_1_percent',
  'p75_tokens_per_1_percent',
  'minimum_tokens_per_1_percent',
  'maximum_tokens_per_1_percent',
  'quota_percent_per_million_tokens',
  'cached_input_percent',
  'credits_per_1_percent',
  'sample_count',
  'quota_percent_observed',
  'sample_from',
  'sample_to',
  'cycle_starts_at',
  'time_slice_label',
  'change_from_previous_percent',
  'reset_kind',
  'reset_observed_at',
  'previous_used_percent',
  'current_used_percent',
  'previous_resets_at',
  'resets_at',
  'session_id',
  'date',
  'quota_kind',
  'requests',
  'input_tokens',
  'cached_input_tokens',
  'cache_write_input_tokens',
  'output_tokens',
  'reasoning_output_tokens',
  'total_tokens',
  'standard_equivalent_total_tokens',
  'standard_equivalent_api_usd',
  'api_equivalent_usd',
  'api_cache_savings_usd',
  'codex_credit_equivalent',
  'codex_credit_cache_savings',
  'api_priced_tokens',
  'credit_priced_tokens',
  'long_context_requests',
  'source_session_count',
  'range_session_count',
  'comparison_session_count',
  'session_count',
  'total_chat_turns',
  'median_session_turns',
  'p90_session_turns',
  'maximum_session_turns',
  'average_context_compactions',
  'session_turns_minimum',
  'session_turns_maximum',
  'median_uncached_input_tokens_per_turn',
  'median_cached_input_tokens_per_turn',
  'median_cache_write_input_tokens_per_turn',
  'median_output_tokens_per_turn',
  'median_reasoning_output_tokens_per_turn',
  'median_total_tokens_per_turn',
  'median_api_equivalent_usd_per_turn',
  'api_pricing_coverage_percent',
  'lowest_token_ranges',
  'lowest_api_cost_ranges',
  'sustained_increase_minimum_turns',
  'sustained_increase_maximum_turns',
  'sustained_increase_percent',
  'p25_peak_context_tokens',
  'p75_peak_context_tokens',
  'is_lowest_token_range',
  'is_lowest_api_cost_range',
  'api_priced_sessions',
  'excluded_unsupported_source_sessions',
  'excluded_incomplete_sessions',
  'excluded_no_owned_turn_sessions',
  'excluded_open_sessions',
  'excluded_outside_range_sessions',
  'excluded_no_usage_sessions',
  'excluded_unknown_model_sessions',
  'excluded_mixed_model_sessions',
  'mixed_service_tier_sessions',
  'unknown_service_tier_sessions',
  'model_token_shares',
  'valuation_kind',
] as const;

function csvExport(investigation: CodexUsageInvestigation, rows: readonly CodexUsageInternalRow[]) {
  const lines = [
    ...turnSpeedRows(investigation),
    ...sessionLengthRows(investigation),
    ...quotaCycleRows(investigation),
  ];
  for (const estimate of investigation.quotaYield?.estimates ?? []) {
    lines.push({
      record_kind: 'QUOTA_YIELD_ESTIMATE',
      generated_at: investigation.generatedAt,
      range: investigation.range,
      time_zone: investigation.timeZone,
      granularity: investigation.granularity,
      algorithm_version: investigation.quotaYield?.algorithmVersion ?? null,
      attribution: estimate.attribution,
      plan_type: estimate.planType,
      limit_id: estimate.limitId,
      quota_kind: estimate.quotaKind,
      window_kind: estimate.windowKind,
      window_duration_minutes: estimate.windowDurationMins,
      model: estimate.model,
      service_tier: estimate.serviceTier,
      tokens_per_subscription_quota_1_percent: estimate.medianTokensPerOnePercent,
      mean_tokens_per_1_percent: estimate.tokensPerOnePercent,
      median_non_cached_tokens_per_1_percent: estimate.medianNonCachedTokensPerOnePercent,
      median_tokens_per_1_percent: estimate.medianTokensPerOnePercent,
      p25_tokens_per_1_percent: estimate.percentile25TokensPerOnePercent,
      p75_tokens_per_1_percent: estimate.percentile75TokensPerOnePercent,
      minimum_tokens_per_1_percent: estimate.minimumTokensPerOnePercent,
      maximum_tokens_per_1_percent: estimate.maximumTokensPerOnePercent,
      quota_percent_per_million_tokens: estimate.quotaPercentPerMillionTokens,
      cached_input_percent: estimate.cachedInputPercent,
      credits_per_1_percent: estimate.codexCreditsPerOnePercent,
      sample_count: estimate.sampleCount,
      quota_percent_observed: estimate.quotaPercentObserved,
      sample_from: estimate.firstAt,
      sample_to: estimate.lastAt,
      requests: estimate.requestCount,
      total_tokens: estimate.totalTokens,
      codex_credit_equivalent: estimate.codexCredits,
      valuation_kind: 'observed_tokens_per_subscription_quota_percent',
    });
  }
  for (const slice of investigation.quotaYield?.timeSlices ?? []) {
    lines.push({
      record_kind: 'QUOTA_YIELD_TIME_SLICE',
      generated_at: investigation.generatedAt,
      range: investigation.range,
      time_zone: slice.timeZone,
      granularity: slice.granularity,
      algorithm_version: investigation.quotaYield?.algorithmVersion ?? null,
      attribution: slice.attribution,
      plan_type: slice.planType,
      limit_id: slice.limitId,
      quota_kind: slice.quotaKind,
      window_kind: slice.windowKind,
      window_duration_minutes: slice.windowDurationMins,
      model: slice.model,
      service_tier: slice.serviceTier,
      tokens_per_subscription_quota_1_percent: slice.medianTokensPerOnePercent,
      mean_tokens_per_1_percent: slice.tokensPerOnePercent,
      median_non_cached_tokens_per_1_percent: slice.medianNonCachedTokensPerOnePercent,
      median_tokens_per_1_percent: slice.medianTokensPerOnePercent,
      p25_tokens_per_1_percent: slice.percentile25TokensPerOnePercent,
      p75_tokens_per_1_percent: slice.percentile75TokensPerOnePercent,
      quota_percent_per_million_tokens: slice.quotaPercentPerMillionTokens,
      cached_input_percent: slice.cachedInputPercent,
      credits_per_1_percent: slice.codexCreditsPerOnePercent,
      sample_count: slice.sampleCount,
      quota_percent_observed: slice.quotaPercentObserved,
      sample_from: slice.observedFrom,
      sample_to: slice.observedTo,
      time_slice_label: slice.label,
      change_from_previous_percent: slice.changeFromPreviousPercent,
      requests: slice.requestCount,
      total_tokens: slice.totalTokens,
      valuation_kind: 'observed_tokens_per_subscription_quota_percent_time_slice',
    });
  }
  for (const sample of investigation.quotaYield?.samples ?? []) {
    lines.push({
      record_kind: 'QUOTA_YIELD_SAMPLE',
      generated_at: investigation.generatedAt,
      range: investigation.range,
      time_zone: investigation.timeZone,
      granularity: investigation.granularity,
      algorithm_version: investigation.quotaYield?.algorithmVersion ?? null,
      attribution: sample.attribution,
      plan_type: sample.planType,
      limit_id: sample.limitId,
      quota_kind: sample.quotaKind,
      window_kind: sample.windowKind,
      window_duration_minutes: sample.windowDurationMins,
      model: sample.model,
      service_tier: sample.serviceTier,
      tokens_per_subscription_quota_1_percent: sample.tokensPerOnePercent,
      mean_tokens_per_1_percent: sample.tokensPerOnePercent,
      median_non_cached_tokens_per_1_percent:
        (Math.max(0, sample.inputTokens - sample.cachedInputTokens) + sample.outputTokens) /
        sample.quotaPercentConsumed,
      quota_percent_per_million_tokens: sample.quotaPercentPerMillionTokens,
      cached_input_percent: sample.inputTokens > 0 ? (sample.cachedInputTokens / sample.inputTokens) * 100 : 0,
      credits_per_1_percent: sample.codexCreditsPerOnePercent,
      sample_count: 1,
      quota_percent_observed: sample.quotaPercentConsumed,
      sample_from: sample.from,
      sample_to: sample.to,
      resets_at: sample.resetsAt,
      total_tokens: sample.totalTokens,
      requests: sample.requestCount,
      input_tokens: sample.inputTokens,
      cached_input_tokens: sample.cachedInputTokens,
      cache_write_input_tokens: sample.cacheWriteInputTokens,
      output_tokens: sample.outputTokens,
      reasoning_output_tokens: sample.reasoningOutputTokens,
      codex_credit_equivalent: sample.codexCredits,
      valuation_kind: 'observed_tokens_per_subscription_quota_percent',
    });
  }
  for (const observation of investigation.quotaYield?.resetObservations ?? []) {
    lines.push({
      record_kind: 'QUOTA_BOUNDARY_OBSERVATION',
      generated_at: investigation.generatedAt,
      range: investigation.range,
      time_zone: investigation.timeZone,
      granularity: investigation.granularity,
      algorithm_version: investigation.quotaYield?.algorithmVersion ?? null,
      plan_type: observation.planType,
      limit_id: observation.limitId,
      quota_kind: observation.quotaKind,
      window_kind: observation.windowKind,
      window_duration_minutes: observation.windowDurationMins,
      reset_kind: observation.kind,
      reset_observed_at: observation.observedAt,
      previous_used_percent: observation.previousUsedPercent,
      current_used_percent: observation.currentUsedPercent,
      previous_resets_at: observation.previousResetsAt,
      resets_at: observation.currentResetsAt,
      valuation_kind: 'observed_quota_sequence_boundary',
    });
  }
  for (const row of rows) {
    lines.push({
      record_kind: 'USAGE',
      generated_at: investigation.generatedAt,
      range: investigation.range,
      time_zone: investigation.timeZone,
      granularity: investigation.granularity,
      model: row.model,
      service_tier: row.serviceTier,
      inferred_service_tier_tokens: row.inferredServiceTierTokens,
      sample_from: row.firstAt,
      sample_to: row.lastAt,
      session_id: row.sessionId,
      date: row.date,
      quota_kind: row.quotaKind,
      requests: row.requestCount,
      input_tokens: row.usage.inputTokens,
      cached_input_tokens: row.usage.cachedInputTokens,
      cache_write_input_tokens: row.usage.cacheWriteInputTokens,
      output_tokens: row.usage.outputTokens,
      reasoning_output_tokens: row.usage.reasoningOutputTokens,
      total_tokens: row.usage.totalTokens,
      api_equivalent_usd: row.apiEquivalentUsd,
      api_cache_savings_usd: row.apiCacheSavingsUsd,
      codex_credit_equivalent: row.codexCredits,
      codex_credit_cache_savings: row.codexCreditCacheSavings,
      api_priced_tokens: row.apiPricedTokens,
      credit_priced_tokens: row.creditPricedTokens,
      long_context_requests: row.longContextRequestCount,
      valuation_kind: 'public_rate_equivalent_not_billed_spend',
    });
  }
  if (!lines.length) {
    lines.push({ record_kind: 'EMPTY', generated_at: investigation.generatedAt, range: investigation.range });
  }
  return `\uFEFF${CSV_HEADERS.join(',')}\r\n${lines
    .map((line) => CSV_HEADERS.map((header) => csvCell(line[header] ?? null)).join(','))
    .join('\r\n')}\r\n`;
}

function jsonExport(investigation: CodexUsageInvestigation, rows: readonly CodexUsageInternalRow[]) {
  return `${JSON.stringify(
    {
      schemaVersion: 11,
      valuationKind: 'public_rate_equivalent_not_billed_spend',
      turnSpeedKind: 'completed_turn_median_duration_ratio',
      quotaYieldKind: 'weekly_quota_observation_segment_tokens_per_observed_quota_percent',
      quotaSpeedNormalizationKind: 'fast_credit_multiplier_to_standard_equivalent_tokens',
      sessionLengthCostKind: 'complete_session_event_date_standard_api_equivalent_per_owned_chat_turn',
      investigation,
      sessionModelDays: rows.map((row) => ({
        sessionId: row.sessionId,
        date: row.date,
        model: row.model,
        serviceTier: row.serviceTier,
        inferredServiceTierTokens: row.inferredServiceTierTokens,
        quotaKind: row.quotaKind,
        firstAt: row.firstAt,
        lastAt: row.lastAt,
        requestCount: row.requestCount,
        ...row.usage,
        apiEquivalentUsd: row.apiEquivalentUsd,
        apiCacheSavingsUsd: row.apiCacheSavingsUsd,
        codexCreditEquivalent: row.codexCredits,
        codexCreditCacheSavings: row.codexCreditCacheSavings,
        apiPricedTokens: row.apiPricedTokens,
        creditPricedTokens: row.creditPricedTokens,
        longContextRequestCount: row.longContextRequestCount,
      })),
    },
    null,
    2,
  )}\n`;
}

export function serializeCodexUsageExport(
  investigation: CodexUsageInvestigation,
  rows: readonly CodexUsageInternalRow[],
  format: CodexUsageExportFormat,
) {
  return format === 'CSV' ? csvExport(investigation, rows) : jsonExport(investigation, rows);
}
