import type { CodexUsageExportFormat, CodexUsageInvestigation } from '@/shared/contracts/codex-usage';
import type { CodexUsageInternalRow } from '@/main/extensions/codex-usage-investigator/session-reader';

function csvCell(value: string | number | null) {
  if (value === null) return '';
  let text = String(value);
  if (/^[=+\-@\t\r]/.test(text)) text = `'${text}`;
  return /[",\r\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text;
}

type CsvRecord = Partial<Record<string, string | number | null>>;

function quotaCycleRows(investigation: CodexUsageInvestigation): CsvRecord[] {
  return (investigation.quotaYield?.cycles ?? []).map((cycle) => ({
    record_kind: 'QUOTA_OBSERVATION_SEGMENT',
    generated_at: investigation.generatedAt,
    range: investigation.range,
    time_zone: investigation.timeZone,
    granularity: investigation.granularity,
    algorithm_version: investigation.quotaYield?.algorithmVersion ?? null,
    calculation_basis: investigation.quotaYield?.calculationBasis ?? null,
    plan_type: cycle.planType,
    limit_id: cycle.limitId,
    quota_kind: cycle.quotaKind,
    window_kind: cycle.windowKind,
    window_duration_minutes: cycle.windowDurationMins,
    tokens_per_subscription_quota_1_percent: cycle.tokensPerOnePercent,
    median_non_cached_tokens_per_1_percent: cycle.nonCachedTokensPerOnePercent,
    cached_input_percent: cycle.cachedInputPercent,
    sample_count: 1,
    quota_percent_observed: cycle.quotaPercentConsumed,
    sample_from: cycle.observedFrom,
    sample_to: cycle.observedTo,
    cycle_starts_at: cycle.startsAt,
    previous_used_percent: cycle.baselineUsedPercent,
    current_used_percent: cycle.maximumUsedPercent,
    resets_at: cycle.resetsAt,
    requests: cycle.requestCount,
    input_tokens: cycle.inputTokens,
    cached_input_tokens: cycle.cachedInputTokens,
    cache_write_input_tokens: cycle.cacheWriteInputTokens,
    output_tokens: cycle.outputTokens,
    reasoning_output_tokens: cycle.reasoningOutputTokens,
    total_tokens: cycle.totalTokens,
    model_token_shares: JSON.stringify(cycle.modelShares),
    valuation_kind: 'weekly_quota_observation_segment_tokens_per_observed_quota_percent',
  }));
}

function csvExport(investigation: CodexUsageInvestigation, rows: readonly CodexUsageInternalRow[]) {
  const headers = [
    'record_kind',
    'generated_at',
    'range',
    'time_zone',
    'granularity',
    'algorithm_version',
    'calculation_basis',
    'attribution',
    'plan_type',
    'limit_id',
    'window_kind',
    'window_duration_minutes',
    'model',
    'service_tier',
    'tokens_per_subscription_quota_1_percent',
    'mean_tokens_per_1_percent',
    'median_non_cached_tokens_per_1_percent',
    'median_tokens_per_1_percent',
    'p25_tokens_per_1_percent',
    'p75_tokens_per_1_percent',
    'minimum_tokens_per_1_percent',
    'maximum_tokens_per_1_percent',
    'quota_percent_per_million_tokens',
    'cached_input_percent',
    'credits_per_1_percent',
    'sample_count',
    'quota_percent_observed',
    'sample_from',
    'sample_to',
    'cycle_starts_at',
    'time_slice_label',
    'change_from_previous_percent',
    'reset_kind',
    'reset_observed_at',
    'previous_used_percent',
    'current_used_percent',
    'previous_resets_at',
    'resets_at',
    'session_id',
    'date',
    'quota_kind',
    'requests',
    'input_tokens',
    'cached_input_tokens',
    'cache_write_input_tokens',
    'output_tokens',
    'reasoning_output_tokens',
    'total_tokens',
    'api_equivalent_usd',
    'api_cache_savings_usd',
    'codex_credit_equivalent',
    'api_priced_tokens',
    'credit_priced_tokens',
    'long_context_requests',
    'model_token_shares',
    'valuation_kind',
  ] as const;
  const lines = quotaCycleRows(investigation);
  for (const estimate of investigation.quotaYield?.estimates ?? []) {
    lines.push({
      record_kind: 'QUOTA_YIELD_ESTIMATE',
      generated_at: investigation.generatedAt,
      range: investigation.range,
      time_zone: investigation.timeZone,
      granularity: investigation.granularity,
      algorithm_version: investigation.quotaYield?.algorithmVersion ?? null,
      attribution: estimate.attribution,
      plan_type: estimate.planType,
      limit_id: estimate.limitId,
      quota_kind: estimate.quotaKind,
      window_kind: estimate.windowKind,
      window_duration_minutes: estimate.windowDurationMins,
      model: estimate.model,
      service_tier: estimate.serviceTier,
      tokens_per_subscription_quota_1_percent: estimate.medianTokensPerOnePercent,
      mean_tokens_per_1_percent: estimate.tokensPerOnePercent,
      median_non_cached_tokens_per_1_percent: estimate.medianNonCachedTokensPerOnePercent,
      median_tokens_per_1_percent: estimate.medianTokensPerOnePercent,
      p25_tokens_per_1_percent: estimate.percentile25TokensPerOnePercent,
      p75_tokens_per_1_percent: estimate.percentile75TokensPerOnePercent,
      minimum_tokens_per_1_percent: estimate.minimumTokensPerOnePercent,
      maximum_tokens_per_1_percent: estimate.maximumTokensPerOnePercent,
      quota_percent_per_million_tokens: estimate.quotaPercentPerMillionTokens,
      cached_input_percent: estimate.cachedInputPercent,
      credits_per_1_percent: estimate.codexCreditsPerOnePercent,
      sample_count: estimate.sampleCount,
      quota_percent_observed: estimate.quotaPercentObserved,
      sample_from: estimate.firstAt,
      sample_to: estimate.lastAt,
      requests: estimate.requestCount,
      total_tokens: estimate.totalTokens,
      codex_credit_equivalent: estimate.codexCredits,
      valuation_kind: 'observed_tokens_per_subscription_quota_percent',
    });
  }
  for (const slice of investigation.quotaYield?.timeSlices ?? []) {
    lines.push({
      record_kind: 'QUOTA_YIELD_TIME_SLICE',
      generated_at: investigation.generatedAt,
      range: investigation.range,
      time_zone: slice.timeZone,
      granularity: slice.granularity,
      algorithm_version: investigation.quotaYield?.algorithmVersion ?? null,
      attribution: slice.attribution,
      plan_type: slice.planType,
      limit_id: slice.limitId,
      quota_kind: slice.quotaKind,
      window_kind: slice.windowKind,
      window_duration_minutes: slice.windowDurationMins,
      model: slice.model,
      service_tier: slice.serviceTier,
      tokens_per_subscription_quota_1_percent: slice.medianTokensPerOnePercent,
      mean_tokens_per_1_percent: slice.tokensPerOnePercent,
      median_non_cached_tokens_per_1_percent: slice.medianNonCachedTokensPerOnePercent,
      median_tokens_per_1_percent: slice.medianTokensPerOnePercent,
      p25_tokens_per_1_percent: slice.percentile25TokensPerOnePercent,
      p75_tokens_per_1_percent: slice.percentile75TokensPerOnePercent,
      quota_percent_per_million_tokens: slice.quotaPercentPerMillionTokens,
      cached_input_percent: slice.cachedInputPercent,
      credits_per_1_percent: slice.codexCreditsPerOnePercent,
      sample_count: slice.sampleCount,
      quota_percent_observed: slice.quotaPercentObserved,
      sample_from: slice.observedFrom,
      sample_to: slice.observedTo,
      time_slice_label: slice.label,
      change_from_previous_percent: slice.changeFromPreviousPercent,
      requests: slice.requestCount,
      total_tokens: slice.totalTokens,
      valuation_kind: 'observed_tokens_per_subscription_quota_percent_time_slice',
    });
  }
  for (const sample of investigation.quotaYield?.samples ?? []) {
    lines.push({
      record_kind: 'QUOTA_YIELD_SAMPLE',
      generated_at: investigation.generatedAt,
      range: investigation.range,
      time_zone: investigation.timeZone,
      granularity: investigation.granularity,
      algorithm_version: investigation.quotaYield?.algorithmVersion ?? null,
      attribution: sample.attribution,
      plan_type: sample.planType,
      limit_id: sample.limitId,
      quota_kind: sample.quotaKind,
      window_kind: sample.windowKind,
      window_duration_minutes: sample.windowDurationMins,
      model: sample.model,
      service_tier: sample.serviceTier,
      tokens_per_subscription_quota_1_percent: sample.tokensPerOnePercent,
      mean_tokens_per_1_percent: sample.tokensPerOnePercent,
      median_non_cached_tokens_per_1_percent:
        (Math.max(0, sample.inputTokens - sample.cachedInputTokens) + sample.outputTokens) /
        sample.quotaPercentConsumed,
      quota_percent_per_million_tokens: sample.quotaPercentPerMillionTokens,
      cached_input_percent: sample.inputTokens > 0 ? (sample.cachedInputTokens / sample.inputTokens) * 100 : 0,
      credits_per_1_percent: sample.codexCreditsPerOnePercent,
      sample_count: 1,
      quota_percent_observed: sample.quotaPercentConsumed,
      sample_from: sample.from,
      sample_to: sample.to,
      resets_at: sample.resetsAt,
      total_tokens: sample.totalTokens,
      requests: sample.requestCount,
      input_tokens: sample.inputTokens,
      cached_input_tokens: sample.cachedInputTokens,
      cache_write_input_tokens: sample.cacheWriteInputTokens,
      output_tokens: sample.outputTokens,
      reasoning_output_tokens: sample.reasoningOutputTokens,
      codex_credit_equivalent: sample.codexCredits,
      valuation_kind: 'observed_tokens_per_subscription_quota_percent',
    });
  }
  for (const observation of investigation.quotaYield?.resetObservations ?? []) {
    lines.push({
      record_kind: 'QUOTA_BOUNDARY_OBSERVATION',
      generated_at: investigation.generatedAt,
      range: investigation.range,
      time_zone: investigation.timeZone,
      granularity: investigation.granularity,
      algorithm_version: investigation.quotaYield?.algorithmVersion ?? null,
      plan_type: observation.planType,
      limit_id: observation.limitId,
      quota_kind: observation.quotaKind,
      window_kind: observation.windowKind,
      window_duration_minutes: observation.windowDurationMins,
      reset_kind: observation.kind,
      reset_observed_at: observation.observedAt,
      previous_used_percent: observation.previousUsedPercent,
      current_used_percent: observation.currentUsedPercent,
      previous_resets_at: observation.previousResetsAt,
      resets_at: observation.currentResetsAt,
      valuation_kind: 'observed_quota_sequence_boundary',
    });
  }
  for (const row of rows) {
    lines.push({
      record_kind: 'USAGE',
      generated_at: investigation.generatedAt,
      range: investigation.range,
      time_zone: investigation.timeZone,
      granularity: investigation.granularity,
      model: row.model,
      service_tier: row.serviceTier,
      sample_from: row.firstAt,
      sample_to: row.lastAt,
      session_id: row.sessionId,
      date: row.date,
      quota_kind: row.quotaKind,
      requests: row.requestCount,
      input_tokens: row.usage.inputTokens,
      cached_input_tokens: row.usage.cachedInputTokens,
      cache_write_input_tokens: row.usage.cacheWriteInputTokens,
      output_tokens: row.usage.outputTokens,
      reasoning_output_tokens: row.usage.reasoningOutputTokens,
      total_tokens: row.usage.totalTokens,
      api_equivalent_usd: row.apiEquivalentUsd,
      api_cache_savings_usd: row.apiCacheSavingsUsd,
      codex_credit_equivalent: row.codexCredits,
      api_priced_tokens: row.apiPricedTokens,
      credit_priced_tokens: row.creditPricedTokens,
      long_context_requests: row.longContextRequestCount,
      valuation_kind: 'public_rate_equivalent_not_billed_spend',
    });
  }
  if (!lines.length) {
    lines.push({ record_kind: 'EMPTY', generated_at: investigation.generatedAt, range: investigation.range });
  }
  return `\uFEFF${headers.join(',')}\r\n${lines
    .map((line) => headers.map((header) => csvCell(line[header] ?? null)).join(','))
    .join('\r\n')}\r\n`;
}

function jsonExport(investigation: CodexUsageInvestigation, rows: readonly CodexUsageInternalRow[]) {
  return `${JSON.stringify(
    {
      schemaVersion: 6,
      valuationKind: 'public_rate_equivalent_not_billed_spend',
      quotaYieldKind: 'weekly_quota_observation_segment_tokens_per_observed_quota_percent',
      investigation,
      sessionModelDays: rows.map((row) => ({
        sessionId: row.sessionId,
        date: row.date,
        model: row.model,
        serviceTier: row.serviceTier,
        quotaKind: row.quotaKind,
        firstAt: row.firstAt,
        lastAt: row.lastAt,
        requestCount: row.requestCount,
        ...row.usage,
        apiEquivalentUsd: row.apiEquivalentUsd,
        apiCacheSavingsUsd: row.apiCacheSavingsUsd,
        codexCreditEquivalent: row.codexCredits,
        apiPricedTokens: row.apiPricedTokens,
        creditPricedTokens: row.creditPricedTokens,
        longContextRequestCount: row.longContextRequestCount,
      })),
    },
    null,
    2,
  )}\n`;
}

export function serializeCodexUsageExport(
  investigation: CodexUsageInvestigation,
  rows: readonly CodexUsageInternalRow[],
  format: CodexUsageExportFormat,
) {
  return format === 'CSV' ? csvExport(investigation, rows) : jsonExport(investigation, rows);
}
